# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from block_chain_grpc import blockchain_pb2 as block__chain__grpc_dot_blockchain__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in block_chain_grpc/blockchain_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BlockchainServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetChainInfor = channel.unary_unary(
                '/blockchain.BlockchainService/GetChainInfor',
                request_serializer=block__chain__grpc_dot_blockchain__pb2.Empty.SerializeToString,
                response_deserializer=block__chain__grpc_dot_blockchain__pb2.ChainInfor.FromString,
                _registered_method=True)
        self.StreamChain = channel.unary_stream(
                '/blockchain.BlockchainService/StreamChain',
                request_serializer=block__chain__grpc_dot_blockchain__pb2.Empty.SerializeToString,
                response_deserializer=block__chain__grpc_dot_blockchain__pb2.Block.FromString,
                _registered_method=True)


class BlockchainServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetChainInfor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamChain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BlockchainServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetChainInfor': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChainInfor,
                    request_deserializer=block__chain__grpc_dot_blockchain__pb2.Empty.FromString,
                    response_serializer=block__chain__grpc_dot_blockchain__pb2.ChainInfor.SerializeToString,
            ),
            'StreamChain': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamChain,
                    request_deserializer=block__chain__grpc_dot_blockchain__pb2.Empty.FromString,
                    response_serializer=block__chain__grpc_dot_blockchain__pb2.Block.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'blockchain.BlockchainService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('blockchain.BlockchainService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BlockchainService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetChainInfor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blockchain.BlockchainService/GetChainInfor',
            block__chain__grpc_dot_blockchain__pb2.Empty.SerializeToString,
            block__chain__grpc_dot_blockchain__pb2.ChainInfor.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamChain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/blockchain.BlockchainService/StreamChain',
            block__chain__grpc_dot_blockchain__pb2.Empty.SerializeToString,
            block__chain__grpc_dot_blockchain__pb2.Block.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
